(function(){
  const $=id=>document.getElementById(id); const state={applicationCode:'',lessons:[],watched:{},timers:{}};
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function msg(t,cls){const el=$('message');el.textContent=t||'';el.className=`msg ${cls||''}`;}
  async function api(url,opts){const res=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(opts?.headers||{})},...(opts||{})});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'Request failed');return data;}
  function getRef(){const qs=new URLSearchParams(location.search);let ss={};try{ss=JSON.parse(sessionStorage.getItem('cwf_partner_ref')||'{}')}catch(_){}return qs.get('code')||qs.get('application_code')||ss.code||'';}
  async function resolveCode(){let code=getRef();if(code)return code;const t=await api('/tech/partner-onboarding');return t.partner?.application?.application_code||'';}
  function percent(){return state.lessons.length?Math.round(state.lessons.filter(l=>l.completed).length/state.lessons.length*100):0;}
  function renderLessons(data){const app=data.application||{},course=data.course||{};state.lessons=data.lessons||[];$('academyPanel').classList.remove('hidden');$('courseTitle').textContent=course.title||'Basic Partner Course';$('applicantName').textContent=`${app.full_name||'-'} · ${app.application_code||''}`;try{sessionStorage.setItem('cwf_partner_ref',JSON.stringify({code:app.application_code,phone:app.phone||''}))}catch(_){}const p=percent();$('progressBadge').textContent=`${p}%`;$('progressBadge').className=`badge ${p===100?'ok':'warn'}`;$('progressBar').style.width=`${p}%`;
    $('lessons').innerHTML=state.lessons.map(l=>{const min=Number(l.min_watch_seconds||60);const watched=Number(l.watched_seconds||0);const remain=Math.max(0,min-watched);const ready=l.completed||remain<=0;return `<article class="lesson"><div class="top"><div><h3>${esc(l.sort_order)}. ${esc(l.lesson_title)}</h3><p>${esc(l.body_text||'')}</p></div><span class="badge ${l.completed?'ok':'warn'}">${l.completed?'เรียนครบแล้ว':'ต้องดูบทเรียน'}</span></div><div class="video"><b>วิดีโออบรม / เนื้อหาที่ต้องดู</b><div style="margin-top:7px;color:rgba(255,255,255,.86);font-weight:800">${l.video_url?`กดเปิดวิดีโอ แล้วกลับมายืนยันเมื่อดูครบ`:'ยังไม่มีไฟล์วิดีโอจริงในระบบ ใช้บทเรียนนี้เป็นเนื้อหาบังคับชั่วคราว และต้องรอเวลาให้ครบก่อนยืนยัน'}</div><span class="timer" id="timer-${l.id}">${l.completed?'ดูครบแล้ว':`เหลือ ${remain} วินาที`}</span></div><div class="actions"><button class="btn secondary" data-watch="${l.id}" type="button">เริ่มดูบทเรียน</button>${l.video_url?`<a class="btn ghost" href="${esc(l.video_url)}" target="_blank" rel="noopener">เปิดวิดีโอ</a>`:''}<button class="btn primary" data-complete="${l.id}" type="button" ${ready?'':'disabled'}>${l.completed?'ยืนยันอีกครั้ง':'ยืนยันว่าเรียนบทนี้จบ'}</button></div></article>`}).join(''); if(p===100) loadExam().catch(e=>msg(e.message,'err'));}
  function startWatch(id){const lesson=state.lessons.find(l=>String(l.id)===String(id));if(!lesson)return;const min=Number(lesson.min_watch_seconds||60);state.watched[id]=Math.max(Number(lesson.watched_seconds||0),state.watched[id]||0);if(state.timers[id])return;state.timers[id]=setInterval(()=>{state.watched[id]++;const remain=Math.max(0,min-state.watched[id]);const el=$(`timer-${id}`);if(el)el.textContent=remain?`เหลือ ${remain} วินาที`:'ดูครบแล้ว สามารถยืนยันได้';const btn=document.querySelector(`[data-complete="${CSS.escape(String(id))}"]`);if(remain<=0&&btn){btn.disabled=false;clearInterval(state.timers[id]);delete state.timers[id];}},1000);}
  async function complete(id){const watched=Math.max(state.watched[id]||0,Number(state.lessons.find(l=>String(l.id)===String(id))?.watched_seconds||0));await api(`/partner/academy/${encodeURIComponent(state.applicationCode)}/lessons/${encodeURIComponent(id)}/complete`,{method:'POST',body:JSON.stringify({watched_seconds:watched})});msg('บันทึกบทเรียนแล้ว','success');await loadAcademy();}
  async function loadAcademy(){state.applicationCode=await resolveCode();if(!state.applicationCode)throw new Error('ไม่พบใบสมัคร กรุณาเข้าใหม่จากหน้าแอพช่าง');renderLessons(await api(`/partner/academy/${encodeURIComponent(state.applicationCode)}`));}
  async function loadExam(){const data=await api(`/partner/academy/${encodeURIComponent(state.applicationCode)}/exam`);$('examPanel').classList.remove('hidden');$('examTitle').textContent=data.exam?.title||'Basic Partner Exam';$('questions').innerHTML=(data.questions||[]).map(q=>`<div class="exam-card"><b>${esc(q.sort_order)}. ${esc(q.question_text)}</b><div>${(q.choices_json||[]).map((c,i)=>`<label class="choice"><input type="radio" name="q-${q.id}" value="${i}"><span>${esc(c)}</span></label>`).join('')}</div></div>`).join('');}
  async function submitExam(){const answers={};document.querySelectorAll('#questions input[type="radio"]:checked').forEach(i=>{answers[i.name.replace('q-','')]=Number(i.value)});const total=document.querySelectorAll('.exam-card').length;if(Object.keys(answers).length<total)throw new Error('กรุณาตอบคำถามให้ครบทุกข้อ');const data=await api(`/partner/academy/${encodeURIComponent(state.applicationCode)}/exam/submit`,{method:'POST',body:JSON.stringify({answers})});msg(`ส่งข้อสอบแล้ว คะแนน ${data.attempt?.score_percent}% ${data.passed?'ผ่าน':'ยังไม่ผ่าน'}`,data.passed?'success':'err');}
  document.addEventListener('click',e=>{const w=e.target.closest('[data-watch]');if(w)startWatch(w.dataset.watch);const c=e.target.closest('[data-complete]');if(c)complete(c.dataset.complete).catch(err=>msg(err.message,'err'));});$('btnSubmitExam')?.addEventListener('click',()=>submitExam().catch(e=>msg(e.message,'err')));document.addEventListener('DOMContentLoaded',()=>loadAcademy().catch(e=>msg(e.message,'err')));
})();
