(function(){
  const $=id=>document.getElementById(id); const state={code:'',lessons:[],questions:[]};
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  async function api(url,opts){const res=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(opts?.headers||{})},...(opts||{})});const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.error||'Request failed');return data;}
  function getStoredRef(){try{return JSON.parse(sessionStorage.getItem('cwf_partner_ref')||'{}');}catch(_){return{};}}
  async function resolveCode(){const u=new URL(location.href);let code=u.searchParams.get('code')||u.searchParams.get('application_code')||'';if(!code)code=getStoredRef().code||'';if(code)return code;const tech=await api('/tech/partner-onboarding');if(!tech.partner)throw new Error('ไม่พบข้อมูลพาร์ทเนอร์ของบัญชีนี้');return tech.partner.application.application_code;}
  function completion(){return state.lessons.length?Math.round(state.lessons.filter(l=>l.completed).length/state.lessons.length*100):0;}
  function render(data){const app=data.application||{};const course=data.course||{};state.lessons=data.lessons||[];$('academyPanel').classList.remove('hidden');$('courseTitle').textContent=course.title||'Basic Partner Course';$('applicantName').textContent=`${app.full_name||'-'} • ${app.status||'-'}`;$('progressBadge').textContent=`${completion()}%`;$('progressBadge').className=`badge ${completion()===100?'ok':''}`;$('lessons').innerHTML=state.lessons.map(l=>`<article class="lesson"><div style="display:flex;justify-content:space-between;gap:10px"><div><b>${esc(l.sort_order||'')}. ${esc(l.lesson_title)}</b><div style="line-height:1.65;margin-top:8px">${esc(l.body_text||'')}</div><div class="muted" style="margin-top:8px">${l.completed?'เสร็จแล้ว':'ยังไม่เสร็จ'}</div></div><span class="badge ${l.completed?'ok':''}">${l.completed?'เสร็จแล้ว':'รอทำ'}</span></div><button class="${l.completed?'ghost':'primary'}" data-complete="${esc(l.id)}" style="margin-top:12px">${l.completed?'ยืนยันอีกครั้ง':'ทำบทเรียนนี้เสร็จ'}</button></article>`).join('');$('lessons').querySelectorAll('[data-complete]').forEach(b=>b.onclick=async()=>{await api(`/partner/academy/${encodeURIComponent(state.code)}/lessons/${encodeURIComponent(b.dataset.complete)}/complete`,{method:'POST',body:'{}'});await load();});}
  async function loadExam(){const data=await api(`/partner/academy/${encodeURIComponent(state.code)}/exam`);state.questions=data.questions||[];$('examBox').innerHTML=`<form id="examForm">${state.questions.map((q,i)=>`<article class="question"><b>${i+1}. ${esc(q.question_text)}</b><div class="choices">${(q.choices_json||[]).map((c,idx)=>`<label class="choice"><input type="radio" name="q_${q.id}" value="${idx}" required><span>${esc(c)}</span></label>`).join('')}</div></article>`).join('')}<button class="primary" type="submit" style="width:100%;margin-top:10px">ส่งข้อสอบ</button></form>`;$('examForm').onsubmit=async e=>{e.preventDefault();const answers={};state.questions.forEach(q=>{answers[String(q.id)]=Number(new FormData(e.target).get(`q_${q.id}`));});const r=await api(`/partner/academy/${encodeURIComponent(state.code)}/exam/submit`,{method:'POST',body:JSON.stringify({answers})});alert(`คะแนน ${r.attempt.score_percent}% ${r.passed?'ผ่าน':'ไม่ผ่าน'}`);};}
  async function load(){try{$('message').textContent='กำลังโหลด...';state.code=await resolveCode();const data=await api(`/partner/academy/${encodeURIComponent(state.code)}`);$('message').textContent='';render(data);}catch(e){$('message').textContent=e.message;$('message').className='msg err';}}
  $('btnLoadExam')?.addEventListener('click',()=>loadExam().catch(e=>alert(e.message||'โหลดข้อสอบไม่สำเร็จ')));load();
})();